In [ ]:
Printing Arrays

In [1]:
import numpy as np

In [ ]:
1D array

In [14]:
a=np.arange(6)

In [15]:
print(a)

[0 1 2 3 4 5]


In [ ]:
2D array

In [22]:
l=np.arange(24).reshape(2,3,4)

In [23]:
print(l)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
3D array

In [9]:
c=np.arange(24).reshape(2,3,4)

In [10]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
np.set_printoptions(threshold=np.nan)

In [24]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [ ]:
Arithmetic Operations on Array

In [ ]:
If the dimensions of 2 arrays are disimilar, we can't perform operations. However NumPy allows it

In [33]:
c=np.array([10,10,10])
d=np.array([5,5,5])

In [34]:
c+d

array([15, 15, 15])

In [36]:
c/d

array([2., 2., 2.])

In [37]:
c%3

array([1, 1, 1], dtype=int32)

In [39]:
c<35

array([ True,  True,  True])

In [41]:
c>25

array([False, False, False])

In [42]:
c**2

array([100, 100, 100], dtype=int32)

In [ ]:
dot function or method

In [43]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

print('A:\n',A)
print('B:\n',B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [44]:
A*B     #This gives element wise multiplication

array([[2, 0],
       [0, 4]])

In [45]:
A.dot(B)    #This gives the matrix multiplication

array([[5, 4],
       [3, 4]])

In [46]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [ ]:
Modifying an existing array rather than creating a new one

In [47]:
a*=3
a

array([ 0,  3,  6,  9, 12, 15])

In [ ]:
Unary Operators

In [ ]:
c=np.array[12,15,18,20]

In [52]:
c.sum()

30

In [55]:
c.min()

10

In [56]:
c.max()

10